apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{.Values.gateway.name}}
    namespace:  {{.Values.gateway.namespace}}
  hostnames:
  - {{ .Values.gateway.url }}
  rules:
    - backendRefs:
      - name: {{ .Release.Name }}-qdrant
        port: {{ (index .Values.qdrant.service.ports 0).port }}
