apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}
  namespace: {{.Values.gateway.namespace}}
spec:
  hosts:
    - {{ .Values.gateway.url }}
  location: MESH_INTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: {{ .Release.Name }}-qdrant.{{ .Release.Namespace }}.svc.cluster.local
      ports:
        http: {{ (index .Values.qdrant.service.ports 0).port }}
